apiVersion: v1
kind: Secret
metadata:
  name: secret-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "https://989421027713.dkr.ecr.us-east-1.amazonaws.com": {
          "auth": "QUtJQTRHWDNXQVBCSUYyN041VVA=:RHZuaU9Kb1Z5eWx3WE9JcXExUGFScmdHYkxxM0hCSzRKNmdQU1FHRQ=="
        }
      }
    }
