name: Deploy to production

on:
  push:
    branches: [main]

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG}}

jobs:
  deploy:
    name: Build image
    runs-on: "self-hosted"

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Load secrets from AWS secret manager and save to .env
      run: aws secretsmanager get-secret-value --secret-id api_std_lib --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > .env

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: api-std-lib
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
    
    - name: Debug Kubectl Configuration
      run: |
       cat $HOME/.kube/config

    - name: Deploy App(Auth)
      uses: actions-hub/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f k9s/aws-auth.yaml
    
    - name: Deploy App(Deployment)
      uses: actions-hub/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f k9s/deployment.yaml

    - name: Deploy App(Service)
      uses: actions-hub/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f k9s/service.yaml
    
    - name: Deploy App(Issuer)
      uses: actions-hub/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f k9s/issuer.yaml

    - name: Deploy App(Ingress)
      uses: actions-hub/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f k9s/ingress.yaml
    
    - name: Deploy App(Restart)
      uses: actions-hub/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: rollout restart deploy api-std-lib-api-deployment