name: Deploy to production

on:
  push:
    branches: [main]

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG}}

jobs:
  deploy:
    name: Build image and push to Docker Hub
    runs-on: "self-hosted"

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.3'
      id: install

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Load secrets from AWS secret manager and save to .env
      run: aws secretsmanager get-secret-value --secret-id api_std_lib --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > .env

    - name: Build, tag, and push image to Docker Hub
      env:
        DOCKER_HUB_REPO: youngjun827/api-std-lib
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $DOCKER_HUB_REPO:$IMAGE_TAG -t $DOCKER_HUB_REPO:latest .
        docker push $DOCKER_HUB_REPO:latest
    
    - name: Debug Kubectl Configuration
      run: |
       cat $HOME/.kube/config

    - name: Deploy App(Auth)
      run: kubectl apply -f k8s/aws-auth.yaml
    
    - name: Deploy App(Deployment)
      run: kubectl apply -f k8s/deployment.yaml

    - name: Deploy App(Service)
      run: kubectl apply -f k8s/service.yaml

    - name: Deploy App(Restart)
      run: kubectl rollout restart deploy api-std-lib-api-deployment
